unstable_features              = true
max_width                      = 110
single_line_if_else_max_width  = 70
single_line_let_else_max_width = 75
struct_lit_width               = 55
struct_variant_width           = 55
chain_width                    = 90
fn_call_width                  = 90
control_brace_style            = "ClosingNextLine"
edition                        = "2024"
match_arm_leading_pipes        = "Always"
use_small_heuristics           = "default"
